### PR TITLE
upgrade to Engine.IO Protocol v4: reverse ping/pong mechanism

### PR DESCRIPTION
**Pull request by HashZhang**

### CODE REVIEW

**Comment by HashZhang** [comment]
for #835, but it is a broken change and cannot be ported to the version for socket.io v1/2
It may be better to add various branch for various version compatibility

**Comment by mrniko** [comment]
Thanks for contribution. Please correct conflicts with latest codebase.

**Comment by luoqiz** [comment]
waiting ...

**Comment by HashZhang** [comment]
> Thanks for contribution. Please correct conflicts with latest codebase.

resolved~

**Comment by mrniko** [comment]
Thank you!

**Pull request merged**
