### PR TITLE
Fix the issue that ack response timeout cause NPE

### PR DESCRIPTION
**Pull request by BlueSodaWater**
**What's the purpose of this PR**
Fix the issue that ack response timeout cause NPE

**Which issue(s) this PR fixes:**
Fixes https://github.com/mrniko/netty-socketio/issues/947

### CODE REVIEW

**Comment by malinGH** [comment]
Is it better to write ‘frame.release()’ ？
because the 'release()' method releases memory

**Comment by malinGH** [comment]
Is it better to write 'frame.release()'?
because the release() method releases memory

**Comment by BlueSodaWater** [comment]
> Is it better to write 'frame.release()'? because the release() method releases memory

make sense

**Comment by mrniko** [comment]
Thanks for contribution!

**Pull request merged**
